name: FreeRDP

on: workflow_dispatch

jobs:
  build:
  
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: RUN
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/ArHiHello/potential-fiesta/main/start.bat -OutFile start.bat
